sudo: false
language: node_js
node_js: "7"

script:
  - npm test

after_script:
  - npm run tslint
  - npm install istanbul jasmine-node codecov
  - istanbul cover --include-all-sources jasmine-node spec
  - bash <(curl -s https://codecov.io/bash)
