sudo: false
language: node_js
node_js: "7"

script:
  - npm test

after_script:
  - npm run tslint
  - npm install karma karma-typescript phantomjs-prebuilt
  - ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS

  - bash <(curl -s https://codecov.io/bash)
